### ISSUE TITLE
TypeError in natasha/span.py

### ISSUE THREAD

**Issue by katjazin** [natasha/natasha#104]
Hello! 
Thanks a lot for Natasha )! It looks really nice. 
I try to use Ner-Part of Demo and become follow message:

```
>>> doc.tag_ner(ner_tagger)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ez/.local/lib/python3.6/site-packages/natasha/doc.py", line 142, in tag_ner
    tag_ner_doc(self, tagger)
  File "/home/ez/.local/lib/python3.6/site-packages/natasha/doc.py", line 265, in tag_ner_doc
    doc.envelop_span_tokens()
  File "/home/ez/.local/lib/python3.6/site-packages/natasha/doc.py", line 157, in envelop_span_tokens
    envelop_span_tokens(self.tokens, self.spans)
  File "/home/ez/.local/lib/python3.6/site-packages/natasha/doc.py", line 278, in envelop_span_tokens
    for group, span in zip(groups, spans):
  File "/home/ez/.local/lib/python3.6/site-packages/natasha/span.py", line 27, in envelop_spans
    while index < len(spans):
TypeError: object of type 'NoneType' has no len()
>>> print(doc.spans[:5])
[DocSpan(start=6, stop=13, type='LOC', text='Израиля'), DocSpan(start=17, stop=24, type='LOC', text='Украине'), DocSpan(start=25, stop=35, type='PER', text='Йоэль Лион'), DocSpan(start=89, stop=106, type='LOC', text='Львовской области'), DocSpan(start=152, stop=158, type='LOC', text='России')]
```
Is is my problem or Yours?
Thanks a lot
Katja

**Comment by katjazin** [comment]
doc.segment(segmenter) solves the problem
thanks
