### ISSUE TITLE
Не происходит разбор имен из примера

### ISSUE THREAD

**Issue by andrvm** [natasha/natasha#105]
```
from natasha import (
    Segmenter,
    MorphVocab,
    NewsEmbedding,
    NewsMorphTagger,
    NewsSyntaxParser,
    NewsNERTagger,    
    PER,
    NamesExtractor,
    Doc
)

morph_vocab = MorphVocab()
segmenter = Segmenter()
emb = NewsEmbedding()
morph_tagger = NewsMorphTagger(emb)
syntax_parser = NewsSyntaxParser(emb)
ner_tagger = NewsNERTagger(emb)
names_extractor = NamesExtractor(morph_vocab)

    text = '''
    Посол Израиля на Украине Йоэль Лион признался, что пришел в шок, узнав о решении властей Львовской области объявить 2019
     год годом лидера запрещенной в России Организации украинских националистов (ОУН) Степана Бандеры. 
     Свое заявление он разместил в Twitter. «Я не могу понять, как прославление тех, 
     кто непосредственно принимал участие в ужасных антисемитских преступлениях, помогает бороться с антисемитизмом и ксенофобией. 
     Украина не должна забывать о преступлениях, совершенных против украинских евреев, и никоим образом не отмечать их через почитание их исполнителей», 
     — написал дипломат. 11 декабря Львовский областной совет принял решение провозгласить 2019 год в регионе годом Степана Бандеры 
     в связи с празднованием 110-летия со дня рождения лидера ОУН (Бандера родился 1 января 1909 года). В июле аналогичное решение принял
      Житомирский областной совет. В начале месяца с предложением к президенту страны Петру Порошенко вернуть Бандере звание Героя Украины 
      обратились депутаты Верховной Рады. Парламентарии уверены, что признание Бандеры национальным героем поможет в борьбе с подрывной 
      деятельностью против Украины в информационном поле, а также остановит «распространение мифов, созданных российской пропагандой».
       Степан Бандера (1909-1959) был одним из лидеров Организации украинских националистов, выступающей за создание независимого 
       государства на территориях с украиноязычным населением.
     В 2010 году в период президентства Виктора Ющенко Бандера был посмертно признан Героем Украины, однако впоследствии это решение было отменено судом. 
    '''
doc = Doc(text)
doc.segment(segmenter)
doc.tag_morph(morph_tagger)
doc.parse_syntax(syntax_parser)
doc.tag_ner(ner_tagger)
for span in doc.spans:
     if span.type == PER:
        span.extract_fact(names_extractor)       
`
```
Получаю ошибку:
`Traceback (most recent call last):
  File "/scripts/aik_complaints.py", line 71, in <module>
    span.extract_fact(names_extractor)
  File "/usr/local/lib/python3.9/site-packages/natasha/doc.py", line 83, in extract_fact
    match = extractor.find(self.normal)
  File "/usr/local/lib/python3.9/site-packages/natasha/extractors.py", line 47, in find
    match = self.parser.find(text)
  File "/usr/local/lib/python3.9/site-packages/yargy/parser.py", line 295, in find
    for match in self.findall(text):
  File "/usr/local/lib/python3.9/site-packages/yargy/parser.py", line 289, in findall
    states = self.matches(text)
  File "/usr/local/lib/python3.9/site-packages/yargy/parser.py", line 276, in matches
    chart = self.chart(text, all=all)
  File "/usr/local/lib/python3.9/site-packages/yargy/parser.py", line 260, in chart
    chart = Chart(tokens)
  File "/usr/local/lib/python3.9/site-packages/yargy/parser.py", line 27, in __init__
    self.tokens = list(tokens)
  File "/usr/local/lib/python3.9/site-packages/yargy/tagger.py", line 15, in __call__
    for token in tokens:
  File "/usr/local/lib/python3.9/site-packages/yargy/tokenizer.py", line 121, in __call__
    for token in tokens:
  File "/usr/local/lib/python3.9/site-packages/yargy/tokenizer.py", line 99, in __call__
    for match in re.finditer(self.regexp, text):
  File "/usr/local/lib/python3.9/re.py", line 248, in finditer
    return _compile(pattern, flags).finditer(string)
TypeError: expected string or bytes-like object
`

**Comment by andrvm** [comment]
Думаю, что проблема в отсутствии поля fact

**Comment by andrvm** [comment]
Думаю, что проблема в отсутствии поля fact

**Comment by andrvm** [comment]
Для тех кто испытывает те же пробелемы, вот решение:
```
for span in doc.spans:
            if span.type == PER:
                **person = list(names_extractor.find(span.text))**
```
