### ISSUE TITLE
ImportError: cannot import name NamesExtractor

### ISSUE THREAD

**Issue by postfriday** [natasha/natasha#79]
Пытаюсь запустить пример из readme.

Dockerfile:
```dockerfile
FROM python:3.3-alpine

WORKDIR /opt

RUN apk add --no-cache git
RUN pip install --upgrade pip
RUN git clone https://github.com/natasha/yargy.git \
    && cd yargy \
    && pip install -e .
RUN git clone https://github.com/natasha/natasha.git \
    && cd natasha \
    && pip install -e .
COPY . /opt

CMD python /opt/natasha.py
```

natasha.py:
```python
#!usr/bin/env python
# -*- coding: utf-8 -*-

from natasha import NamesExtractor

text = '''
Простите, еще несколько цитат из приговора. «…Отрицал существование
Иисуса и пророка Мухаммеда», «наделял Иисуса Христа качествами
ожившего мертвеца — зомби» [и] «качествами покемонов —
представителей бестиария японской мифологии, тем самым совершил
преступление, предусмотренное статьей 148 УК РФ
'''
extractor = NamesExtractor()
matches = extractor(text)
for match in matches:
    print(match.span, match.fact)
```

Возвращается ошибка ImportError:
```
Sending build context to Docker daemon  19.46kB
Step 1/8 : FROM python:3.3-alpine
3.3-alpine: Pulling from library/python
90f4dba627d6: Pull complete
a615e2cf13bb: Pull complete
0690617e12d1: Pull complete
033251e905b4: Pull complete
c17f36d5ae04: Pull complete
Digest: sha256:32b65b0dd11df5fb4dcf1e0f6bb05007b6b84270959ab27b618b513321ef6d6a
Status: Downloaded newer image for python:3.3-alpine
 ---> b68bfb13f0fa
Step 2/8 : WORKDIR /opt
 ---> Running in 41adc15acaca
Removing intermediate container 41adc15acaca
 ---> 329242f778b1
Step 3/8 : RUN apk add --no-cache git
 ---> Running in 7c744d474e3f
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
(1/4) Installing libssh2 (1.7.0-r0)
(2/4) Installing libcurl (7.60.0-r1)
(3/4) Installing pcre (8.38-r1)
(4/4) Installing git (2.8.6-r0)
Executing busybox-1.24.2-r13.trigger
OK: 48 MiB in 38 packages
Removing intermediate container 7c744d474e3f
 ---> 7c32e813dd41
Step 4/8 : RUN pip install --upgrade pip
 ---> Running in b1b5c5935cd9
Collecting pip
  Downloading https://files.pythonhosted.org/packages/0f/74/ecd13431bcc456ed390b44c8a6e917c1820365cbebcb6a8974d1cd045ab4/pip-10.0.1-py2.py3-none-any.whl (1.3MB)
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
Successfully installed pip-10.0.1
Removing intermediate container b1b5c5935cd9
 ---> c4f9dbd9eb18
Step 5/8 : RUN git clone https://github.com/natasha/yargy.git     && cd yargy     && pip install -e .
 ---> Running in 4ba6bc5003c6
Cloning into 'yargy'...
DEPRECATION: Python 3.3 supported has been deprecated and support for it will be dropped in the future. Please upgrade your Python.
Obtaining file:///opt/yargy
Collecting pymorphy2==0.8 (from yargy==0.12.0)
  Downloading https://files.pythonhosted.org/packages/a3/33/fff9675c68b5f6c63ec8c6e6ff57827dda28a1fa5b2c2d727dffff92dd47/pymorphy2-0.8-py2.py3-none-any.whl (46kB)
Collecting backports.functools-lru-cache==1.3 (from yargy==0.12.0)
  Downloading https://files.pythonhosted.org/packages/d4/40/0b1db94fdfd71353ae67ec444ff28e0a7ecc25212d1cb94c291b6cd226f9/backports.functools_lru_cache-1.3-py2.py3-none-any.whl
Collecting dawg-python>=0.7 (from pymorphy2==0.8->yargy==0.12.0)
  Downloading https://files.pythonhosted.org/packages/6a/84/ff1ce2071d4c650ec85745766c0047ccc3b5036f1d03559fd46bb38b5eeb/DAWG_Python-0.7.2-py2.py3-none-any.whl
Collecting docopt>=0.6 (from pymorphy2==0.8->yargy==0.12.0)
  Downloading https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz
Collecting pymorphy2-dicts<3.0,>=2.4 (from pymorphy2==0.8->yargy==0.12.0)
  Downloading https://files.pythonhosted.org/packages/02/51/2465fd4f72328ab50877b54777764d928da8cb15b74e2680fc1bd8cb3173/pymorphy2_dicts-2.4.393442.3710985-py2.py3-none-any.whl (7.1MB)
Building wheels for collected packages: docopt
  Running setup.py bdist_wheel for docopt: started
  Running setup.py bdist_wheel for docopt: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/9b/04/dd/7daf4150b6d9b12949298737de9431a324d4b797ffd63f526e
Successfully built docopt
Installing collected packages: dawg-python, docopt, pymorphy2-dicts, pymorphy2, backports.functools-lru-cache, yargy
  Running setup.py develop for yargy
Successfully installed backports.functools-lru-cache-1.3 dawg-python-0.7.2 docopt-0.6.2 pymorphy2-0.8 pymorphy2-dicts-2.4.393442.3710985 yargy
Removing intermediate container 4ba6bc5003c6
 ---> 0a9cb2fa22b4
Step 6/8 : RUN git clone https://github.com/natasha/natasha.git     && cd natasha     && pip install -e .
 ---> Running in c8c0f3aeac9a
Cloning into 'natasha'...
DEPRECATION: Python 3.3 supported has been deprecated and support for it will be dropped in the future. Please upgrade your Python.
Obtaining file:///opt/natasha
Requirement already satisfied: yargy in /opt/yargy (from natasha==0.10.0) (0.12.0)
Requirement already satisfied: pymorphy2==0.8 in /usr/local/lib/python3.3/site-packages (from yargy->natasha==0.10.0) (0.8)
Requirement already satisfied: backports.functools-lru-cache==1.3 in /usr/local/lib/python3.3/site-packages (from yargy->natasha==0.10.0) (1.3)
Requirement already satisfied: pymorphy2-dicts<3.0,>=2.4 in /usr/local/lib/python3.3/site-packages (from pymorphy2==0.8->yargy->natasha==0.10.0) (2.4.393442.3710985)
Requirement already satisfied: dawg-python>=0.7 in /usr/local/lib/python3.3/site-packages (from pymorphy2==0.8->yargy->natasha==0.10.0) (0.7.2)
Requirement already satisfied: docopt>=0.6 in /usr/local/lib/python3.3/site-packages (from pymorphy2==0.8->yargy->natasha==0.10.0) (0.6.2)
Installing collected packages: natasha
  Running setup.py develop for natasha
Successfully installed natasha
Removing intermediate container c8c0f3aeac9a
 ---> bdff2b0aba06
Step 7/8 : COPY . /opt
 ---> 40115a2bd69f
Step 8/8 : CMD python /opt/natasha.py
 ---> Running in 7619bd14dcf3
Removing intermediate container 7619bd14dcf3
 ---> 4dffe7d81604
Successfully built 4dffe7d81604
Successfully tagged natasha:6A63BCE3-B6D7-4C82-BD75-E04D02806A24
Traceback (most recent call last):
  File "/opt/natasha.py", line 4, in <module>
    from natasha import NamesExtractor
  File "/opt/natasha.py", line 4, in <module>
    from natasha import NamesExtractor
ImportError: cannot import name NamesExtractor
```

Пробовал устанавливать по разному, как описано в тикете: https://github.com/natasha/natasha/issues/23#issue-257031037.

Результат тот же.

Подскажите, что я делаю не так?

**Comment by postfriday** [comment]
То же самое для Python 3.8:

Dockerfile:
```dockerfile
FROM python:3.8-alpine

WORKDIR /opt

RUN apk add --no-cache git
RUN pip install --upgrade pip
RUN git clone https://github.com/natasha/yargy.git \
    && cd yargy \
    && pip install -e .
RUN git clone https://github.com/natasha/natasha.git \
    && cd natasha \
    && pip install -e .
COPY . /opt

CMD python /opt/natasha.py
```

Тут ошибка:  **ImportError: cannot import name 'NamesExtractor' from partially initialized module 'natasha' (most likely due to a circular import) (/opt/natasha.py)**

```
Sending build context to Docker daemon  19.46kB
Step 1/8 : FROM python:3.8-alpine
3.8-alpine: Pulling from library/python
e6b0cf9c0882: Pull complete
da0e9bf0cc60: Pull complete
c9ea274ed700: Pull complete
9cfac6ba3733: Pull complete
f6a933c9cadc: Pull complete
Digest: sha256:23f6b2c7c94054a451965e37932716e36b8630461ed635a666f100c441798110
Status: Downloaded newer image for python:3.8-alpine
 ---> 4c30403e92a1
Step 2/8 : WORKDIR /opt
 ---> Running in ddb0fd31396a
Removing intermediate container ddb0fd31396a
 ---> af2d77d31fb2
Step 3/8 : RUN apk add --no-cache git
 ---> Running in 7c1435f86133
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
(1/4) Installing nghttp2-libs (1.40.0-r0)
(2/4) Installing libcurl (7.67.0-r0)
(3/4) Installing pcre2 (10.34-r1)
(4/4) Installing git (2.24.1-r0)
Executing busybox-1.31.1-r8.trigger
OK: 33 MiB in 39 packages
Removing intermediate container 7c1435f86133
 ---> d5ca7f43976d
Step 4/8 : RUN pip install --upgrade pip
 ---> Running in 60c43af8e4be
Requirement already up-to-date: pip in /usr/local/lib/python3.8/site-packages (19.3.1)
Removing intermediate container 60c43af8e4be
 ---> e1c0a74bb402
Step 5/8 : RUN git clone https://github.com/natasha/yargy.git     && cd yargy     && pip install -e .
 ---> Running in b7d78b7a1517
Cloning into 'yargy'...
Obtaining file:///opt/yargy
Collecting pymorphy2==0.8
  Downloading https://files.pythonhosted.org/packages/a3/33/fff9675c68b5f6c63ec8c6e6ff57827dda28a1fa5b2c2d727dffff92dd47/pymorphy2-0.8-py2.py3-none-any.whl (46kB)
Collecting backports.functools-lru-cache==1.3
  Downloading https://files.pythonhosted.org/packages/d4/40/0b1db94fdfd71353ae67ec444ff28e0a7ecc25212d1cb94c291b6cd226f9/backports.functools_lru_cache-1.3-py2.py3-none-any.whl
Collecting docopt>=0.6
  Downloading https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz
Collecting pymorphy2-dicts<3.0,>=2.4
  Downloading https://files.pythonhosted.org/packages/02/51/2465fd4f72328ab50877b54777764d928da8cb15b74e2680fc1bd8cb3173/pymorphy2_dicts-2.4.393442.3710985-py2.py3-none-any.whl (7.1MB)
Collecting dawg-python>=0.7
  Downloading https://files.pythonhosted.org/packages/6a/84/ff1ce2071d4c650ec85745766c0047ccc3b5036f1d03559fd46bb38b5eeb/DAWG_Python-0.7.2-py2.py3-none-any.whl
Building wheels for collected packages: docopt
  Building wheel for docopt (setup.py): started
  Building wheel for docopt (setup.py): finished with status 'done'
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13704 sha256=5dcd30081be8ba98ad4fdf89c22025055c89700eee043c443d428356648ee085
  Stored in directory: /root/.cache/pip/wheels/9b/04/dd/7daf4150b6d9b12949298737de9431a324d4b797ffd63f526e
Successfully built docopt
Installing collected packages: docopt, pymorphy2-dicts, dawg-python, pymorphy2, backports.functools-lru-cache, yargy
  Running setup.py develop for yargy
Successfully installed backports.functools-lru-cache-1.3 dawg-python-0.7.2 docopt-0.6.2 pymorphy2-0.8 pymorphy2-dicts-2.4.393442.3710985 yargy
Removing intermediate container b7d78b7a1517
 ---> fe615f7440eb
Step 6/8 : RUN git clone https://github.com/natasha/natasha.git     && cd natasha     && pip install -e .
 ---> Running in 6310fc2aafa7
Cloning into 'natasha'...
Obtaining file:///opt/natasha
Requirement already satisfied: yargy in /opt/yargy (from natasha==0.10.0) (0.12.0)
Requirement already satisfied: pymorphy2==0.8 in /usr/local/lib/python3.8/site-packages (from yargy->natasha==0.10.0) (0.8)
Requirement already satisfied: backports.functools-lru-cache==1.3 in /usr/local/lib/python3.8/site-packages (from yargy->natasha==0.10.0) (1.3)
Requirement already satisfied: dawg-python>=0.7 in /usr/local/lib/python3.8/site-packages (from pymorphy2==0.8->yargy->natasha==0.10.0) (0.7.2)
Requirement already satisfied: pymorphy2-dicts<3.0,>=2.4 in /usr/local/lib/python3.8/site-packages (from pymorphy2==0.8->yargy->natasha==0.10.0) (2.4.393442.3710985)
Requirement already satisfied: docopt>=0.6 in /usr/local/lib/python3.8/site-packages (from pymorphy2==0.8->yargy->natasha==0.10.0) (0.6.2)
Installing collected packages: natasha
  Running setup.py develop for natasha
Successfully installed natasha
Removing intermediate container 6310fc2aafa7
 ---> 1b0477abc3cd
Step 7/8 : COPY . /opt
 ---> 347d53e618aa
Step 8/8 : CMD python /opt/natasha.py
 ---> Running in 939c24de5794
Removing intermediate container 939c24de5794
 ---> affc5460de00
Successfully built affc5460de00
Successfully tagged natasha:AA05B478-F027-47E0-9AE7-B8E9B7CD0D77
Traceback (most recent call last):
  File "/opt/natasha.py", line 4, in <module>
    from natasha import NamesExtractor
  File "/opt/natasha.py", line 4, in <module>
    from natasha import NamesExtractor
ImportError: cannot import name 'NamesExtractor' from partially initialized module 'natasha' (most likely due to a circular import) (/opt/natasha.py)
```

**Comment by kuk** [comment]
Переименуйте файл natasha.py во что-то другое, например main.py

**Comment by postfriday** [comment]
Божечки, какая досадная ошибка!

Спасибо!
