### ISSUE TITLE
Не парсится предложение из примера

### ISSUE THREAD

**Issue by vorobyovayana** [natasha/natasha#94]
Запускаю код из вашего примера с вашим текстом
from natasha import Segmenter
from natasha import MorphVocab
from natasha import NewsEmbedding
from natasha import NewsMorphTagger
from natasha import NewsSyntaxParser
from natasha import NewsNERTagger
from natasha import PER
from natasha import NamesExtractor
from natasha import Doc

segmenter = Segmenter()
morph_vocab = MorphVocab()

emb = NewsEmbedding()
morph_tagger = NewsMorphTagger(emb)
syntax_parser = NewsSyntaxParser(emb)
ner_tagger = NewsNERTagger(emb)

names_extractor = NamesExtractor(morph_vocab)

text = 'Посол Израиля на Украине Йоэль Лион признался, что пришел в шок, узнав о решении властей Львовской области объявить 2019 год годом лидера запрещенной в России Организации украинских националистов (ОУН) Степана Бандеры. Свое заявление он разместил в Twitter. «Я не могу понять, как прославление тех, кто непосредственно принимал участие в ужасных антисемитских преступлениях, помогает бороться с антисемитизмом и ксенофобией. Украина не должна забывать о преступлениях, совершенных против украинских евреев, и никоим образом не отмечать их через почитание их исполнителей», — написал дипломат. 11 декабря Львовский областной совет принял решение провозгласить 2019 год в регионе годом Степана Бандеры в связи с празднованием 110-летия со дня рождения лидера ОУН (Бандера родился 1 января 1909 года). В июле аналогичное решение принял Житомирский областной совет. В начале месяца с предложением к президенту страны Петру Порошенко вернуть Бандере звание Героя Украины обратились депутаты Верховной Рады. Парламентарии уверены, что признание Бандеры национальным героем поможет в борьбе с подрывной деятельностью против Украины в информационном поле, а также остановит «распространение мифов, созданных российской пропагандой». Степан Бандера (1909-1959) был одним из лидеров Организации украинских националистов, выступающей за создание независимого государства на территориях с украиноязычным населением. В 2010 году в период президентства Виктора Ющенко Бандера был посмертно признан Героем Украины, однако впоследствии это решение было отменено судом. '
doc = Doc(text)

doc.parse_syntax(syntax_parser)
display(doc.tokens[:5])
doc.sents[0].syntax.print()

И получаю ошибку: 
Traceback (most recent call last):
  File "/Users/yanavorobeva/Documents/academics/natasha-master/natasha1.py", line 25, in <module>
    doc.parse_syntax(syntax_parser)
  File "/Users/yanavorobeva/Documents/academics/natasha-master/natasha/doc.py", line 139, in parse_syntax
    parse_syntax_doc(self, parser)
  File "/Users/yanavorobeva/Documents/academics/natasha-master/natasha/doc.py", line 237, in parse_syntax_doc
    chunk = [sent_words(_) for _ in doc.sents]
TypeError: 'NoneType' object is not iterable

**Comment by kuk** [comment]
Перед применением syntax_parser нужно сегментировать документ doc.segment(segmenter), подробнее в https://github.com/natasha/natasha#usage
